### ISSUE TITLE
Sending account id. And waiting until close window

### ISSUE THREAD

**Issue by kzzk** [AshitaXI/Ashita#1]
**Date & Time:3.24.2020 

**Windows Version:win7 X64

**Ashita Version (Type /aver in-game to get this.):v3

**FFXI Version (Type /ver in-game to get this.):finally (last updated )

**Addon / Plugin Name (If applicable.):**

**Additional Information :
It can open retail and injected but
If selecting private several or commands (ffxi-bootmod\pol.exe --server 108.56.171.15 )
It can login but stop at sending account id...till close window.
It can't start the game
/Screenshots / Crashdumps:**

**Comment by atom0s** [comment]
Hello, this generally means your install of the game is bad/incomplete. You will have to resort to getting help from the private server you are trying to play on as this is not an issue related to Ashita.

**Comment by kzzk** [comment]
OK,thanks.
That's last version client can't run under pol.exe.
I get the older version to play
