### ISSUE TITLE
Equipmon ammo count no updating [BUG] 

### ISSUE THREAD

**Issue by GetAwayCoxn** [AshitaXI/Ashita#10]
**Ashita Version** _(Type /ashita in-game to get this.)_
v4.0.0.2

**FFXI Version** _(Type /version in-game to get this.)_
version 30211103_1

**Windows Version** _(ie. Start > About Your PC)_
10 Home 21H1 19043.1348

**Describe The Bug**
Doing some random fishing and equipmon does not update the count on my little worms.

**Steps To Reproduce**
just enable ammo count for equipmon and go fish

**Screenshots**

![Beane_2021 11 11_120214](https://user-images.githubusercontent.com/66495755/141346952-3f3012a6-c41d-49c6-8839-e0ca4e587343.png)

**Additional Information**
I assume other ammo items such as throwing items wont update either, I will check and if for some reason they do I will add comment on this issue

**Comment by atom0s** [comment]
Fixed with: https://github.com/AshitaXI/Ashita-v4beta/commit/21bd58a426075392c0a4f0e6ffccad2465fb5f49
