### ISSUE TITLE
Bellhop crashing client with name entry[BUG] 

### ISSUE THREAD

**Issue by GetAwayCoxn** [AshitaXI/Ashita#11]
**Ashita Version** _(Type /ashita in-game to get this.)_
4.0.0.2

**FFXI Version** _(Type /version in-game to get this.)_
version 30211103_1

**Windows Version** _(ie. Start > About Your PC)_
10 Home 21H1 19043.1288

**Describe The Bug**
I was trying to create an item type group but anytime I make an entry of name type and then load the plugin it crashes the client. When trying to replicate the doc example exactly i was also unable to add the wildcard type but that threw an exception error and did not crash the client. I was able to add an entry with id type and it loaded correctly. When trying to narrow down the name type conflict i tried multiple types of item names, single word, multiple word, with +1, etc. I also tried a two word item name using an underscore instead of a blank space although the example doc showed a blank space. All of these item name options just described crashed the client immediately. 

**Steps To Reproduce**
Update the bellhop settings xml file to include an entry of name type with any item name and load the plugin
Examples:
This will crash:
```
<itemtypes>
<type name="Trash">
	<entry name="Pebble" />
</type>
</itemtypes>
```

This will throw an error but not crash (see screenshot):
```
<itemtypes>
<type name="Trash">
	<entry wildcard="W*Crystal" />
</type>
</itemtypes>
```

This will work:
```
<itemtypes>
<type name="Trash">
	<entry id="17296" />
</type>
</itemtypes>
```

**Screenshots**
This is the error that the wildcard type puked out:

![Beane_2021 11 11_181029](https://user-images.githubusercontent.com/66495755/141388500-6e0cf4cf-f5a5-4985-9c9b-c210cdca1150.png)

**Additional Information**
Not sure if this helps but this also works:
```
<itemtypes>
<type name="Trash">
</type>
</itemtypes>
```

**Comment by ThornyFFXI** [comment]
This should be resolved.

**Comment by GetAwayCoxn** [comment]
Verified to be working correctly now thank you!
