### ISSUE TITLE
Chatmon is extra chatty [BUG] 

### ISSUE THREAD

**Issue by GetAwayCoxn** [AshitaXI/Ashita#12]
Ashita Version (Type /ashita in-game to get this.)
4.0.0.2

FFXI Version (Type /version in-game to get this.)
version 30211103_1

Windows Version (ie. Start > About Your PC)
10 Home 21H1 19043.1288

**Describe The Bug**
Most times but not all the time Chatmon will play the inventory full message upon initial log in and/or zones. I of course verified that my inventory was not full. Another thing I noticed that is semi related is Chatmon was prompting the you're being talked about audio almost every single kill at an apex party working on exemplar  points.

**Steps To Reproduce**
For the first situation just have chatmon loaded to default settings and log in, then zone a couple times.

For the other situation I went out and tried to narrow down what was going on, I think it might be related to earning exemplar points but after killing mulltiple lv of mobs to eliminate the exemplar point theory I can't seem to narrow it down. I can only say for sure that it happens on various types of apex mobs and DI dragons. I can also say that it has nothing to do with giving the kill shot as last night I was on brd at apex camp and it was near 100% of the time but i never killed anything myself.

**Screenshots**
N/A

**Additional Information**
For the inventory full message is there way to make the check frequency pause all together during zone in/log in perhaps?

**Comment by atom0s** [comment]
Fixed with: https://github.com/AshitaXI/Ashita-v4beta/commit/dd18574a18d0c2b320d4f271fc7dd88b9a4372c1
