### ISSUE TITLE
Extremely minor FPS addon issue [BUG] 

### ISSUE THREAD

**Issue by GetAwayCoxn** [AshitaXI/Ashita#13]
Ashita Version (Type /ashita in-game to get this.)
4.0.0.2

FFXI Version (Type /version in-game to get this.)
version 30211103_1

Windows Version (ie. Start > About Your PC)
10 Home 21H1 19043.1288

**Describe The Bug**
Not even really sure if this is bug or working as intended. Version 3 and 4 both have the default.txt scripts binding F12 to "/fps show"
In v3 people are used to that cycling between showing and not showing. In v4 it does not behave the same way, maybe by design? If it is supposed to cycle, then this is a very minor bug. If it is not supposed to cycle like it did in v3 then I would suggest changing the default.txt to bind F12 to "/fps" instead as that cycles just fine and you will avoid a bunch of random comments on discord about how to make the red numbers go away when you release this to the masses.

**Steps To Reproduce**
Load via default.txt script, then push F12 a couple of times.

**Screenshots**
n/a

**Additional Information**
n/a

**Comment by atom0s** [comment]
This will be addressed in the next update to the beta repo. (Holding off since the next update will break the SDK again.)

For now, you can just edit the default.txt to use: `/fps` instead for toggling.

**Comment by GetAwayCoxn** [comment]
Of course, sounds good. I was mostly worried about when this goes more public, more common user experience etc. Thank you for quick reply!

**Comment by atom0s** [comment]
This is now live with: https://github.com/AshitaXI/Ashita-v4beta/commit/8e01ada06eae95d4ef931376adcbd6faaa7f3bbe
