### ISSUE TITLE
Recast not registering Cascade JA [BUG] 

### ISSUE THREAD

**Issue by GetAwayCoxn** [AshitaXI/Ashita#14]
**Ashita Version** _(Type /ashita in-game to get this.)_
4.0.0.2

**FFXI Version** _(Type /version in-game to get this.)_
30211103_1

**Windows Version** _(ie. Start > About Your PC)_
10 Home 21H1 build 19043.1348

**Describe The Bug**
When using the BLM job ability Cascade, recast does not display the name of the ability, but it does display the correct recast time.

**Steps To Reproduce**
Have recast loaded, be on BLM main, use Cascade.

**Screenshots**
This third displayed JA is cascade, the recast time is correct.
![Igotudis_2021 11 16_214348](https://user-images.githubusercontent.com/66495755/142131386-95344270-19cc-44be-9aa9-78df32d31ba1.png)

**Additional Information**
N/A

**Comment by atom0s** [comment]
Fixed with: https://github.com/AshitaXI/Ashita-v4beta/commit/518dccb7d408ce0d893dfda2faee684a4824b69c

**Comment by atom0s** [comment]
This is now live with: https://github.com/AshitaXI/Ashita-v4beta/commit/8e01ada06eae95d4ef931376adcbd6faaa7f3bbe
