### ISSUE TITLE
[BUG] onevent addon crash

### ISSUE THREAD

**Issue by ThornyFFXI** [AshitaXI/Ashita#15]
**Describe The Bug**
After calling 'removeall' or any variant, the events table is assigned as a generic lua table on line 153.  Subsequently, the next incoming text event will attempt to call 'events:ieach' on it and crash.  Line 153 should be changed to assign a table using sugar libs.

**Comment by atom0s** [comment]
Fixed with: https://github.com/AshitaXI/Ashita-v4beta/commit/af879b33d86ccbdff6ee7b4c25cc81e966a58d90
