### ISSUE TITLE
Silent Addon and Silent Alias boot options not working [BUG] 

### ISSUE THREAD

**Issue by GetAwayCoxn** [AshitaXI/Ashita#16]
**Ashita Version** _(Type /ashita in-game to get this.)_
4.0.0.4

**FFXI Version** _(Type /version in-game to get this.)_
30211103_2

**Windows Version** _(ie. Start > About Your PC)_
10 Home, 21H1, Build 19043.1348

**Describe The Bug**
Setting the 'addons.silent' and 'aliases.silent' options to '1' in the boot file is still allowing addon loads/unloads and alias related messages to appear in the game chat log.

**Steps To Reproduce**
Set either or both the 'addons.silent' and 'aliases.silent' parameters in the boot file to '1'
Log into game, upon initial load any/all addons or aliases that are present in your startup script will show in the game chat log
You can also manually unload/load an addon after logged into the game to verify the messages will show in the game chat log
You can also manipulate aliases in the game chat to verify the messages will show in the game chat log

**Screenshots**
Request if needed

**Additional Information**
I did the same things above to the 'plugins.silent' and 'keyboard.silentbinds' options in the boot file and those both appear to be working as intended upon load in from startup script or through manual manipulation of plugins/binds while in game.

**Comment by atom0s** [comment]
Theses should now be fixed with: https://github.com/AshitaXI/Ashita-v4beta/commit/6c6e667fd3ee0fc0f4e563dbd152cef72a27476d

Thanks for the reports. :)
