### ISSUE TITLE
[BUG] Addon development: strange e.mode in text_in event

### ISSUE THREAD

**Issue by Syllendel** [AshitaXI/Ashita#18]
**Ashita Version** _(Type /ashita in-game to get this.)_
v4.0.0.4

**FFXI Version** _(Type /version in-game to get this.)_
30211225_1

**Windows Version** _(ie. Start > About Your PC)_
Windows 10 Enterprise LTSC version 1809 build 17763.2452

**Describe The Bug**
Some messages appear with weird e.mode instead of the expected one. I've seen this happen after loading a zone or loading/unloading/reloading any addon or plugin. This last several seconds before going back to normal until the next zone/loading/etc...
When this happens, the messages are still correctly displayed by the game (proper chat window and color).

**Steps To Reproduce**
Add the following in an addon:
```
ashita.events.register('text_in', 'text_in_callback1', function (e)
      if (e.injected) then
            return
      end
      -- tested with a simple print(e.mode) and the issue occurs too
      e.message_modified = "Mode " .. e.mode .. ": " .. e.message
end);
```
Then change zone or unload or load or reload an addon or plugin.

**Screenshots**
![All Play-On-line Games Screenshot 2022 01 13 - 19 13 31 73](https://user-images.githubusercontent.com/25940775/149388123-d26e218f-5015-4a2d-9ed5-addf64600eef.png)

**Additional Information**
![All Play-On-line Games Screenshot 2022 01 13 - 19 00 31 26](https://user-images.githubusercontent.com/25940775/149388472-b3db16c9-ef0d-469d-b844-5e8b9915db78.png)

![All Play-On-line Games Screenshot 2022 01 13 - 19 18 38 99](https://user-images.githubusercontent.com/25940775/149388470-b99bda88-8484-4286-a8e1-19c29fcf915f.png)

![All Play-On-line Games Screenshot 2022 01 13 - 19 19 09 50](https://user-images.githubusercontent.com/25940775/149388390-7af8342b-b46f-40d6-97df-df8107d41f14.png)

![All Play-On-line Games Screenshot 2022 01 13 - 19 00 54 35](https://user-images.githubusercontent.com/25940775/149388459-743f9017-8dd5-4f93-95f3-fae5cce5b49c.png)

![All Play-On-line Games Screenshot 2022 01 13 - 19 10 53 63](https://user-images.githubusercontent.com/25940775/149388465-615d74fd-9746-4442-bccb-9a82e9ec7d94.png)

**Comment by Syllendel** [comment]
Tested again without any other mod/plugin loaded (Restarted the game with an empty default.txt then manually loaded the 'addons' plugin and my addon to display the e.mode). Issue still occurs.

**Comment by atom0s** [comment]
This is expected behavior, Ashita returns the full true mode id as it is in the client since it can hold other useful information. To pull the id itself you can use:

```lua
    -- Obtain the chat mode..
    local mid = bit.band(e.mode_modified,  0x000000FF); -- Or use e.mode if you need the absolute original.
```
