### ISSUE TITLE
[BUG] Pet ability recasts not working after pet is released

### ISSUE THREAD

**Issue by tom21091** [AshitaXI/Ashita#19]
**Ashita Version** _(Type /ashita in-game to get this.)_
v4.0.0.4

**FFXI Version** _(Type /version in-game to get this.)_
30211225_1

**Windows Version** _(ie. Start > About Your PC)_
W10 Version 20H2

**Describe The Bug**
Pet ability recast names are not returned by resource manager after the pet is dismissed. The snips below are from the recast addon in v4.

**Steps To Reproduce**
/load addon recast
Change to SMN, then summon and use a Blood Pact. Note the ability timer.
Release the pet. Note the ability timer name changes to (Unknown)

**Screenshots**
Before dismissing:
![image](https://user-images.githubusercontent.com/8377880/152898837-30cf7a37-43e5-44ce-a36b-af4edd694668.PNG)
After dismissing:
![image](https://user-images.githubusercontent.com/8377880/152898746-967bb23c-00e7-497d-8936-8be1342fc944.png)
(The 3 second recast is the "Release" command)

**Additional Information**
Please include any additional information you feel could help explain the bug/problem and get it resolved.

**Comment by atom0s** [comment]
This is now fixed using a 'fallback' method. 

_Keep in mind due to how this fallback works, it may yield the wrong recast ability name when trying to display 'Unknown' entries that can happen in situations such as what you reported._
