### ISSUE TITLE
[BUG] Ashita v4 with Sandbox sends "Unknown" client version when connecting to Wings

### ISSUE THREAD

**Issue by mehvvy** [AshitaXI/Ashita#2]
**Ashita Version** _(Type /ashita in-game to get this.)_
Ashita_v4_-_Alpha_-_06.10.2021 and Sandbox_v4_-_Alpha_-_06.10.2021

**FFXI Version** _(Type /version in-game to get this.)_
30190305_0, but it's the custom Wings package 

**Windows Version** _(ie. Start > About Your PC)_
Windows 10 Pro 20H2 19042.1052

**Describe The Bug**
I'm trying to use sandbox to connect to Wings (yes, I know...) but get kicked off with FFXI-3101 after selecting a character.

**Steps To Reproduce**
Create an Ashita profile with the necessary sandbox paths for Wings, try to log in with sandbox enabled.
[wings_local.ini.txt](https://github.com/AshitaXI/Ashita/files/6645105/wings_local.ini.txt)

**Screenshots**
n/a

**Additional Information**
I have a local server setup and am able to reproduce the issue that way. When sandbox is enabled, the client version is apparently being sent as "Unknown". When sandbox is disabled, the client version is being sent as "30190305_0". I don't know if this is an error on my end because I don't know how the client version is obtained or how to debug this further. Let me know if there's anything you'd like me to try.

**Comment by atom0s** [comment]
This is not a bug. Sandbox, by default, will ignore the interface keys of the registry that the client uses to 'validate' itself for being patched properly. The patch.ver file is an encrypted file that, when decrypted, contains the client version string that is sent to the lobby server and what's shown when you `/ver` in-game.

This file is encrypted using the interface ids stored in the registry under:

 - JP: HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\PlayOnline\Interface
 - NA: HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\PlayOnlineUS\Interface
 - EU: HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\PlayOnlineEU\Interface

Each key here is aligned to the game content id that is used with PlayOnline.

  - 0001 - Final Fantasy XI
  - 0002 - TetraMaster
  - 1000 - PlayOnline Viewer

Each game/piece of content has its own key and patch.ver file that POL uses to validate the version information. 

In order for the client to properly read the file and send the IDs, you will need to edit the `sandbox.ini` and add the missing valid interface keys for your Wings install.
