### ISSUE TITLE
[BUG] itemwatch does not support new wardrobes

### ISSUE THREAD

**Issue by zcecil** [AshitaXI/Ashita#20]
**Describe The Bug**
itemwatch cannot find items in wardrobe 5-8.

**Steps To Reproduce**
load itemwatch, add an item in wardrobe 5-8.

Near line 360, for x = 0, 12 should be changed to for x = 0, 16.

**Comment by atom0s** [comment]
This is now fixed in the current beta repo via: https://github.com/AshitaXI/Ashita-v4beta/commit/372f800d29dc6089f2e5783aff99c273e29e1339
