### ISSUE TITLE
[BUG] Saving addon settings

### ISSUE THREAD

**Issue by ShiyoKozuki** [AshitaXI/Ashita#3]
**Ashita Version** _(Type /ashita in-game to get this.)_
4.0.02

**FFXI Version** _(Type /version in-game to get this.)_
Topaz private server

**Windows Version** _(ie. Start > About Your PC)_
8.1

**Describe The Bug**
Saving positional settings is a bit buggy.

**Steps To Reproduce**
Load an addon. Move it's position anywhere. Unload addon - > reload addon. It now resets back to the default settings.  Move addon again -> Unload addon - > reload addon, it now properly saves settings.

**Comment by Shirk** [comment]
There's no generic position saving for addons (outside of imgui windows), it would help to know which addon you encountered the bug with.

**Comment by ShiyoKozuki** [comment]
Any addon I've used using
```
ashita.events.register('unload', 'unload_cb', function ()
settings.save();
end);
```
