### ISSUE TITLE
Addons plugin and client crash 

### ISSUE THREAD

**Issue by Sippius** [AshitaXI/Ashita#31]
**Ashita Version** _(Type /ashita in-game to get this.)_
4.1.0.0

**FFXI Version** _(Type /version in-game to get this.)_
30221224_0 - latest retail after 1/9/2023 update

**Windows Version** _(ie. Start > About Your PC)_
Windows 10 Pro 22H2 19045.2364

**Describe The Bug**
Addons throwing an exception when unloading some addons. Game hangs and client crashes. It seems to be related to addons that display.

**Steps To Reproduce**
To try to isolate the problem I loaded Ashita with the provided default.txt and minimal changes to example-retail.ini (no pivot, no sandbox). The only modifications were to name, script, 0001 and 0002 values. I ran the following commands:
- /addon list
- /addon load recast
- /addon unload recast (nothing on cooldown so no display)
- /addon reload checker
- /addon unload move
- /addon unload checker
- /addon unload fps (also tried tparty as a separate experiment)

When unloading fps or tparty the exception is triggered and the client crashes. Also crashes with /addon reload tparty when tparty is already loaded.

**Screenshots**
![image](https://user-images.githubusercontent.com/90542599/211723667-ce9abee2-8726-4499-bc9d-5750e4eacf23.png)

**Additional Information**
Please include any additional information you feel could help explain the bug/problem and get it resolved.

**Comment by Sippius** [comment]
I am having similar issues with the previous version of Ashita (4.0.0.7) as well. I will run the previous Ashita version with a default configuration tomorrow night.

**Comment by atom0s** [comment]
This issue is fixed and will be pushed in the next update. :) Thanks for the report.

**Comment by atom0s** [comment]
This is now pushed live, should be fixed now. :)

**Comment by Sippius** [comment]
Working great so far. Thanks for the fix. I appreciate you and all you do for this game.
