### ISSUE TITLE
Moghouse Buttons not working[BUG] 

### ISSUE THREAD

**Issue by oblivionben** [AshitaXI/Ashita#33]
**Ashita Version** _(Type /ashita in-game to get this.)_
Ashita v4.1.0.2

**FFXI Version** _(Type /version in-game to get this.)_
Horizon FFXI

**Windows Version** _(ie. Start > About Your PC)_
Windows 11

**Describe The Bug**
Talked to both the nomad moogle in Mhara, and in the moghouse. Was able to select the moogle and open the moghouse menu, but when clicking enter on any of the buttons, none of them would open. The sound will signal but nothing opens.

**Steps To Reproduce**
Zoned in and out of the moghouse. Turned off simplelog. Was still unable to access the options in the moghouse.

**Screenshots**

![Capture](https://user-images.githubusercontent.com/122715785/212526077-958b7e25-55fd-4bd0-897d-efe775e87728.PNG)

**Additional Information**
Please include any additional information you feel could help explain the bug/problem and get it resolved.

**Comment by atom0s** [comment]
This is not an issue with Ashita. It is an issue with Horizon. 
You will need to contact them for help.
