### ISSUE TITLE
Expanding the chatlog crashes the game.[BUG] 

### ISSUE THREAD

**Issue by oblivionben** [AshitaXI/Ashita#34]
**Ashita Version** _(Type /ashita in-game to get this.)_
Ashita v4.1.0.2

**FFXI Version** _(Type /version in-game to get this.)_
Horizon FFXI

**Windows Version** _(ie. Start > About Your PC)_
Windows 11

**Describe The Bug**
When expanding the chatlog, the game will crash.

**Steps To Reproduce**
Happens whenever I open the chat window.

**Screenshots**

**Additional Information**
Please include any additional information you feel could help explain the bug/problem and get it resolved.

**Comment by atom0s** [comment]
This is not an issue with Ashita. This is an issue with Horizons install / DAT mods. 
You will need to talk to them for help.
