### ISSUE TITLE
Went to move the Y axis of the map on a larger resolution and the map disappeared. now every time i load/unload or even restart the game, i cannot see the map

### ISSUE THREAD

**Issue by Spegali** [AshitaXI/Ashita#35]
**Ashita Version** _(Type /ashita in-game to get this.)_

**FFXI Version** _(Type /version in-game to get this.)_

**Windows Version** _(ie. Start > About Your PC)_

**Describe The Bug**
Please give a clear, full description of the bug.

**Steps To Reproduce**
Please give a clear, full list of steps to reproduce the bug, if applicable. 

**Screenshots**

**Additional Information**
Please include any additional information you feel could help explain the bug/problem and get it resolved.

**Comment by atom0s** [comment]
Hello, this is a bug related to Minimap not accounting for its scaled size when being moved. Will get this fixed soon.

You can fix the position of Minimap by using `/minimap` in-game to open the settings editor for it, then manually editing the position to bring it back on screen.

**Comment by Spegali** [comment]
Yes that did it! Thanks!
