### ISSUE TITLE
[BUG] Supplies

### ISSUE THREAD

**Issue by SanKyu3k** [AshitaXI/Ashita#36]
**Ashita Version** _(Type /ashita in-game to get this.)_
v4.0.0.6

**FFXI Version** _(Type /version in-game to get this.)_
nothing happens. Chains of Promathia?

**Windows Version** _(ie. Start > About Your PC)_
Windows 10 Home
21H2

**Describe The Bug**
I am of the Bastok nation. I took a supplies mission to Ronfaure, but did not go there before my nation lost that region.  The M. guards (of my nation) do not take back the supplies, and the guard (not of my nation) at the outpost of course wont take it either.  I can't accept a new mission, because I still have the supplies from the impossible mission.  If it's not a bug, do I have to hold on to them and not do supplies missions until my nation takes that region back?

**Steps To Reproduce**
I had accepted the supplies from a Bastok M. guard, maybe at the North Gate.  When I returned, my Rank went from 1 to 2, I donated a stack of Earth Crystals, accepted a new Mission for my Nation (The Emissary), and by then my nation had lost the region for my supplies.  I don't know if that mixed up the flags, and stuck me with the old supplies.  They won't take it back now.

**Screenshots**
n/a

**Additional Information**
n/a

**Comment by ThornyFFXI** [comment]
This github is for the Ashita software your server may be bundling with their installer.  It has no relation to the server itself, and this is almost certainly an issue with the server.  Please figure out what server you are playing on, and provide this data to them.
