### ISSUE TITLE
[BUG] IDirect3DDevice8:CreatePixelShader Does not work

### ISSUE THREAD

**Issue by Jyouya** [AshitaXI/Ashita#39]
**Ashita Version** _(Type /ashita in-game to get this.)_
4.0.0.6

**FFXI Version** _(Type /version in-game to get this.)_
unknown

**Windows Version** _(ie. Start > About Your PC)_
19044.2846

**Describe The Bug**
The function `IDirect3DDevice8:CreatePixelShader()` does not work.  It is not passing the handle outarg to the C function.

**Additional Information**
Line 604 of `idirect3ddevice8.lua` should be changed from
```
local res       = self.lpVtbl.CreatePixelShader(self, pFunction);
```
to
```
local res       = self.lpVtbl.CreatePixelShader(self, pFunction, handle);
```

**Comment by atom0s** [comment]
Thanks for the report, will fix this when I have the time in the near future.

**Comment by atom0s** [comment]
This is now fixed in the latest beta repo updates.
