### ISSUE TITLE
[BUG] I cannot Log in to HorizonXI

### ISSUE THREAD

**Issue by Simiao03** [AshitaXI/Ashita#45]
**Ashita Version** _(Type /ashita in-game to get this.)_
4.0.0.2

**FFXI Version** _(Type /version in-game to get this.)_
HorizonXI

**Windows Version** _(ie. Start > About Your PC)_
Windows 10 22H2

**Describe The Bug**
Please give a clear, full description of the bug.
Cannot log in even with correct username and password.
**Steps To Reproduce**
Please give a clear, full list of steps to reproduce the bug, if applicable. 
Installed the HorizonXI game, launched it, got the screen below, wanted to type in username and password, even if I typed it correctly, it just infinite loop.
**Screenshots**
![image](https://github.com/AshitaXI/Ashita/assets/130000766/e19814f8-8984-45de-80e8-608276b64a73)

**Additional Information**
Please include any additional information you feel could help explain the bug/problem and get it resolved.

**Comment by atom0s** [comment]
Hello, we do not handle support or issues for individual private servers.
You will need to contact Horizon for help with any login issues you are having with their server.

https://discord.gg/horizonxi

**Comment by Simiao03** [comment]
Sorry, I cannot access their community:
![image](https://github.com/AshitaXI/Ashita/assets/130000766/91f7c229-eaee-4c8b-ad75-4965955559e4)

**Comment by Shirk** [comment]
This isn't any of our concerns and we can't fix it for you - the link (`https://discord.gg/horizonxi`) is working just fine, if your browser is so old that it doesn't support TLS-v1.3 then maybe you should not be on the internet with it.

Take that link, open discord, click "Add Server (+)" bottom left in the side bar, then "Join Server (already have an invite)" and type "https://discord.gg/horizonxi" in the dialogue box that opens.
