### ISSUE TITLE
Statustimers[BUG] 

### ISSUE THREAD

**Issue by zaksame** [AshitaXI/Ashita#47]
**Ashita Version** _(Type /ashita in-game to get this.)_
V4

**FFXI Version** _(Type /version in-game to get this.)_
30230704_2

**Windows Version** _(ie. Start > About Your PC)_

10 home
**Describe The Bug**
Please give a clear, full description of the bug.
Status timers is not showing anything outside my own.Target name is showing but nothing else.As per watching video I see both target and subtarget but I am not getting both either or option.I can click target name icon and lock it but again no timers only shows mine.
**Steps To Reproduce**
Please give a clear, full list of steps to reproduce the bug, if applicable. 

**Screenshots**

**Additional Information**
Please include any additional information you feel could help explain the bug/problem and get it resolved.

**Comment by ThornyFFXI** [comment]
This repo is for Ashita, StatusTimers repo is at:
https://github.com/Shirk/statustimers

That said, keep in mind the client does not receive status timer information for trusts or anyone who is not in your party.  So, it is normal to not see your target's buffs unless it is a party member that is an actual character.

**Comment by atom0s** [comment]
Closing as this is not Ashita specific.
