### ISSUE TITLE
Repeater Addon [BUG]

### ISSUE THREAD

**Issue by GetAwayCoxn** [AshitaXI/Ashita#8]
**Ashita Version** _(Type /ashita in-game to get this.)_
Ashita v4.0.0.2

**FFXI Version** _(Type /version in-game to get this.)_
version 30211005_0  (only /ver worked)

**Windows Version** _(ie. Start > About Your PC)_
Windows 10 Home 21H1 

**Describe The Bug**
When using the set command for an item, the double quotes are dropped and it will not work in game because of not having the required double quotes around the item name. 

**Steps To Reproduce**
In game use the set command for an item such as: `/rp set /item "Silt Pouch" <me>`
Then attempt to start with: `/rp start`
Then addon will not save/use the double quotes properly and the item will not be used.

**Screenshots**
Very simple to replicate so no screenshots were taken

**Additional Information**
This might be an issue in the chat library

**Comment by atom0s** [comment]
This should be fixed now with: https://github.com/AshitaXI/Ashita-v4beta/commit/02842d7c8e23a60ad67c333d0ab0cd198594a5ac
