### ISSUE TITLE
Screenshot not hiding equipmon [BUG] 

### ISSUE THREAD

**Issue by GetAwayCoxn** [AshitaXI/Ashita#9]
**Ashita Version** _(Type /ashita in-game to get this.)_
v4.0.0.2

**FFXI Version** _(Type /version in-game to get this.)_
30211005_0

**Windows Version** _(ie. Start > About Your PC)_
10 Home 21H1 19043.1288

**Describe The Bug**
When using /screenshot hide with the addon equipmon loaded, the equipmon overlay still shows on screenshot taken.

**Steps To Reproduce**
Make sure to have the addon equipmon loaded, then in game type: /screenshot hide

**Screenshots**
This screenshot was taken while messing around with the repeater double quote issue the other day, i had equipmon, clock, and minimap loaded at the time. I was about to delete the file since I didnt upload for the other issue and noticed that equipmon overlay still showing up. I was able to replicate easily.

![Beane_2021 11 08_144743](https://user-images.githubusercontent.com/66495755/140983949-44b47df1-dc8a-4305-83cc-f360e11e6f74.png)

**Additional Information**
Please include any additional information you feel could help explain the bug/problem and get it resolved

**Comment by atom0s** [comment]
Fixed with: https://github.com/AshitaXI/Ashita-v4beta/commit/c9115e597f05a9638b12776420f87ee5ccb160ec

Thanks for the report. :)
